### PR TITLE
feat: add sidebar for articles page

### PR DESCRIPTION
**Pull request by vsnikhilvs**
Add a sidebar for the articles page with navigation and some styles

### CODE REVIEW

**Comment by Aksgo** [comment]
@vsnikhilvs create a separate folder in master with your name and add your files separately. We will apply the your changes after some time.

**Comment by vsnikhilvs** [comment]
> @vsnikhilvs create a separate folder in master with your name and add your files separately. We will apply the your changes after some time.

Hey I have updated my files. Created a folder 'vsnikhilvs' and moved all files there

**Comment by Aksgo** [comment]
@vsnikhilvs probably you have not created the folder but directly added to public or the folder is not reflecting here

**Comment by vsnikhilvs** [comment]
> @vsnikhilvs probably you have not created the folder but directly added to public or the folder is not reflecting here

What I have done is, move all my forked files in a single folder, vsnikhilvs, and pushed it.
Could you please walk me through what you think?

**Comment by Aksgo** [comment]
Do not make any changes to original files , just create a separate folder in master with your name and add copy of the edited files to it. Let the original files and folder remain. I will apply your changes manually

**Comment by vsnikhilvs** [comment]
> Do not make any changes to original files , just create a separate folder in master with your name and add copy of the edited files to it. Let the original files and folder remain. I will apply your changes manually

Got it. Will update them shortly.

**Comment by vsnikhilvs** [comment]
Please check now @Aksgo

**Comment by Aksgo** [comment]
@vsnikhilvs there is some misunderstanding. Please don't change the files in public. Sync your repo with latest files then then just place the copy of your files in master only. Do not edit the files in public. I will apply your changes manually due to some issues. Thanks !

**Pull request closed without merging**
