### PR TITLE
Fix drop down menu for article section

### PR DESCRIPTION
**Pull request by Pujan-khunt**
Removed the drop-down menu for larger screens and instead added 3 bars representing the drop-down menu for mobile users

### CODE REVIEW

**Comment by Aksgo** [comment]
can you please upload a screenshot @Pujan-khunt

**Comment by Pujan-khunt** [comment]
image

**Comment by Aksgo** [comment]
Kindly change in index.html also @Pujan-khunt

**Comment by Pujan-khunt** [comment]
> Kindly change in index.html also @Pujan-khunt

Done.

image

**Comment by Aksgo** [comment]
Great work @Pujan-khunt . Thanks

**Pull request merged**
