### PR TITLE
Sucessfully added and linked Dijkstra's Algorithm for shortest paths #9

### PR DESCRIPTION
**Pull request by yeshwanth-ds**
https://github.com/user-attachments/assets/84ca8efa-7c9a-4c7c-92aa-fb1e6c35fa33

### CODE REVIEW

**Comment by Aksgo** [comment]
Kindly open a new PR with the txt file for article in the main folder and the image with same name as txt file name instead of adding yourself the html files, this is breaking the site.

**Comment by Aksgo** [comment]
then I will attach the hacktoberfest accepted label

**Comment by yeshwanth-ds** [comment]
@Aksgo could u please help me here, I dont completly understand what your trying to say.

**Comment by Aksgo** [comment]
Since you are contributing an article, kindly raise a PR with a .txt (notepad) file which should have your article (read contribution.md to understand more) .
You don't need to yourself create and link an html file, our generator.py will take care of that

**Comment by yeshwanth-ds** [comment]
@Aksgo Okay I will add it.

**Comment by yeshwanth-ds** [comment]
@Aksgo I raised a new PR from the information u provided can u evaluate it #24

**Pull request merged**
