### PR TITLE
Adding the error handler and the format handler#15

### PR DESCRIPTION
**Pull request by Suvendu-UI**

### CODE REVIEW

**Comment by Aksgo** [comment]
@Suvendu-UI, firstly sync your fork then apply the changes

**Comment by Suvendu-UI** [comment]
synced and applied

**Comment by Suvendu-UI** [comment]
changes done

**Comment by Aksgo** [comment]
@Suvendu-UI , you are not making changes in latest generator.py file. Please use it and add your code there

**Pull request closed without merging**
