### PR TITLE
added footer

### PR DESCRIPTION
**Pull request by saurav2208**
PR #66

### CODE REVIEW

**Comment by Aksgo** [comment]
@saurav2208 please add a screenshot for approval

**Comment by Aksgo** [comment]
And please add some basic stuffs that a footer have. Thanks

**Comment by saurav2208** [comment]
> And please add some basic stuffs that a footer have. Thanks

Screenshot 2024-10-31 114549
This is the current look. Do you want me to add more?

**Review by Aksgo — APPROVED** [review]
Nice work. Thank you @saurav2208 !

**Comment by saurav2208** [comment]
> Nice work. Thank you @saurav2208 !

Thanks a lot! @Aksgo

**Pull request merged**
