### PR TITLE
Contribution tab added

### PR DESCRIPTION
**Pull request by TilteD24**
Added contribution tab with default section 

Fixes issue #44

### CODE REVIEW

**Comment by Aksgo** [comment]
@TilteD24 , could you please add a screenshot so that I can approve it. Thanks!

**Comment by Aksgo** [comment]
@TilteD24 Could you please redirect the users to a new page instead of sliding down

**Comment by TilteD24** [comment]
ss1
image

**Comment by Aksgo** [comment]
thank you @TilteD24 for contributing!

**Pull request merged**
