### PR TITLE
Added 'More Articles' section 

### PR DESCRIPTION
**Pull request by Kundanikapradhan**
Added 'More Articles' section structure to ArticleTemplate.html and inserted sample content for Huffman Coding article in ArticleList/huffman-coding.html

### CODE REVIEW

**Comment by Kundanikapradhan** [comment]
@Aksgo please check my pr

**Comment by Aksgo** [comment]
@Kundanikapradhan Do not change the content of huffman-coding.html. We want you to add show a sample of more articles in huffman-coding.html

**Comment by Kundanikapradhan** [comment]
Screenshot 2024-10-09 at 10 20 03 AM
Is this fine? @Aksgo

**Comment by Aksgo** [comment]
@Kundanikapradhan, great. Adjust the files accordingly (do not remove any previous content)

**Comment by Kundanikapradhan** [comment]
sure

**Comment by Aksgo** [comment]
@Kundanikapradhan Keep this section out of that black container (that is for articles related things only)

**Comment by Kundanikapradhan** [comment]
Screenshot 2024-10-09 at 10 30 29 AM
is this how you want it? @Aksgo

**Comment by Aksgo** [comment]
Yes,but I think you broke the css above. Ok let's keep the previous one only, push that code only

**Comment by Kundanikapradhan** [comment]
Can you check my pr? @Aksgo

**Comment by Aksgo** [comment]
Thanks @Kundanikapradhan for contribution !

**Review by Aksgo — APPROVED** [review]
approved

**Pull request merged**
