### PR TITLE
Add FAQ tab at the bottom of article template #25

### PR DESCRIPTION
**Pull request by snehautekar05**
Hi @Aksgo,
I wanted to inform you that I have successfully added an FAQ section at the bottom of each article template. This enhancement is designed to address common questions and provide clarity on the topics covered in the articles.
Please review the changes and let me know if you require any further modifications or adjustments.

### CODE REVIEW

**Comment by Aksgo** [comment]
Thank you @snehautekar05 , firstly you css file is okay, but can you just put all those section which you used for faq (that is just the div tags and their classes) in ArticleTemplate.html, and instead of placing faq individually in html files, put the faq content in 4 text files . Our generator.py will automatically place your content there

**Comment by snehautekar05** [comment]
Yup ok ...I will do the changes

**Comment by snehautekar05** [comment]
@Aksgo 
9536d607-f1a9-4285-aff9-651353fd4542
One more thing I noticed just the article content is related to DFS ....But in the title it is given as BFS so can you just check once this.

**Comment by Aksgo** [comment]
thank you for pointing out !

**Comment by snehautekar05** [comment]
But there are no text files for every article, right? Like you mentioned earlier, I have created four .txt files for each article containing FAQs. However, there are no existing .txt files for each article, as the article content is present in each respective HTML file, and the FAQs for each article will be different.
@Aksgo can you just explain this little bit.

**Comment by Aksgo** [comment]
yes we have not added any txt files here, you can just create yourself 4 files with name 'article-name-faq'.txt and push them

**Comment by snehautekar05** [comment]
okk fine!!

**Comment by snehautekar05** [comment]
@Aksgo I have pushed the .txt files.Can you just check it?....and let me know if any changes required.

**Comment by Aksgo** [comment]
thank you @snehautekar05 for contribution !

**Comment by snehautekar05** [comment]
Thank you so much @Aksgo for giving me chance to contribute!!

**Pull request merged**
