### PR TITLE
[ADD]:Comment section

### LINKED ISSUE #36: Add a comments section at bottom of article
1. In the article template add a comment section (only classes and id's , content should not be there as it would be handled by the generator)
2. Add sample content in public/ArticleList/huffman-coding.html
3. Upload its screenshot

### PR DESCRIPTION
**Pull request by dexterousdhruv**
Add a comments section in article template and a sample comments-content in huffman-coding.html

Closes #36

{0E4053C8-79D3-4507-AB00-1C74A4F1F663}

### CODE REVIEW

**Comment by dexterousdhruv** [comment]
@Aksgo   Kindly review the PR.

**Comment by Aksgo** [comment]
@dexterousdhruv thanks for your work ! Please add a little css also to it, and show the comment box also in huffman-coding.html.

**Comment by dexterousdhruv** [comment]
Ok

**Comment by dexterousdhruv** [comment]
@Aksgo  Final result

{84CDAC1F-AAA9-4995-A2F1-AF1E637902FD}

**Comment by Aksgo** [comment]
Thanks for contribution @dexterousdhruv !

**Pull request merged**
