### PR TITLE
Create dp.txt

### PR DESCRIPTION
**Pull request by codewithishu**
Adding articles for dp algorithm

### CODE REVIEW

**Comment by codewithishu** [comment]
@Aksgo please merge my pr

**Comment by Aksgo** [comment]
Please elaborate the concept more @codewithishu

**Comment by codewithishu** [comment]
@Aksgo done!

**Comment by codewithishu** [comment]
@Aksgo please merge my pr I have ellaborated it

**Comment by codewithishu** [comment]
@Aksgo please merge my pr I have ellaborated the concept

**Comment by Aksgo** [comment]
Thank you @codewithishu  for contributing !

**Pull request merged**
