### PR TITLE
Changed background for homepage

### PR DESCRIPTION
**Pull request by Virtual4087**
Issue #46

### CODE REVIEW

**Comment by Aksgo** [comment]
Kindly add a screenshot

**Comment by Virtual4087** [comment]
image_2024-10-08_124949730
Would you rather prefer an image?

**Comment by Aksgo** [comment]
that is not looking good, instead can you add a simple background image and a scroll effect like [this](https://codepen.io/jh3y/pen/MWLPMYL)

**Comment by Virtual4087** [comment]
got it

**Comment by Virtual4087** [comment]
I don't think I can do the parallax effect. It requires too much time. You can unassign me or I can just add an background if you want.

**Comment by Aksgo** [comment]
No issues, kindly submit a good background

**Comment by Virtual4087** [comment]
image
image
image
image
image

Any of these look good to you?

**Comment by Aksgo** [comment]
Nice @Virtual4087, add the last image in public asset, no need to change any files

**Comment by Virtual4087** [comment]
No need to change the code either?

**Comment by Aksgo** [comment]
> No need to change the code either?

No

**Comment by Virtual4087** [comment]
Done but just so you know I had added a black overlay over the background image in the screenshot. I could write it in the code if you want otherwise I've already added the asset.

**Comment by Aksgo** [comment]
Thank you for contributing !

**Pull request merged**
